-- MySQL Script generated by MySQL Workbench
-- Thu May 31 17:17:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbstore`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_user` VARCHAR(45) NOT NULL,
  `email_user` VARCHAR(45) NOT NULL,
  `senha_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`));

-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbstore`.`produtos` (
  `id_produtos` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL,
  `preco_unit` DECIMAL(5,2) NULL,
  `qtd_est` DECIMAL NULL,
  `url_img` VARCHAR(255) NULL,
  PRIMARY KEY (`id_produtos`));


-- -----------------------------------------------------
-- Table `mydb`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbstore`.`notas` (
  `id_notas` INT NOT NULL AUTO_INCREMENT,
  `data_compra` DATE NOT NULL,
  `id_cliente` INT NULL,
  `metodo_pagamento` VARCHAR(45) NULL,
  PRIMARY KEY (`id_notas`));


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbstore`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idendereco`));


-- -----------------------------------------------------
-- Table `mydb`.`itens_nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbstore`.`itens_nota` (
  `qtd` DECIMAL NULL,
  `id_produtos` INT NULL,
  `id_notas` INT NULL);
